subject: null
random_state: 1234

defaults:
  - _self_
  - experiment: null
  - logger: comet

output_dir: /home/mstlaure/projects/rrg-pbellec/mstlaure/phantom_vlb/results
cache_dir: /home/mstlaure/projects/rrg-pbellec/mstlaure/phantom_vlb/models

